name: Push-to-EC2

# Trigger deployment only on push to mqin branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Files
        uses: actions/checkout@v2

      - name: Push to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Deploy Actions
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key
          ssh -o StrictHostKeyChecking=no -i /tmp/private_key ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "bash -s" < /var/www/smky-core/base/deploy/staging/run.sh
          rm /tmp/private_key
