name: Push-to-EC2

# Trigger deployment only on push to mqin branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Files
        uses: actions/checkout@v2

      - name: Push to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}


      - name: Run deployment scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
#          environment: |
#            DB_HOST=${{ secrets.DB_HOST }}
#            DB_PORT=${{ secrets.DB_PORT }}
#            DB_DATABASE=${{ secrets.DB_DATABASE }}
#            DB_USERNAME=${{ secrets.DB_USERNAME }}
#            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          script: |
            sh deploy/staging/run.sh

